2023-01-23 19:48:14,796 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-01-24 23:03:24,958 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-01-25 11:01:49,458 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-01-25 11:02:20,072 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-01-25 11:02:20,072 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-01-25 20:08:14,357 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-01-26 09:27:44,570 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-01-26 09:28:05,321 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-01-27 21:38:43,338 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-01-27 21:51:54,887 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-01-27 21:52:43,723 ERROR: Exception on /createappointment [GET] [in c:\users\kwabe\documents\!python proj\!nea\nea1\nea2\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\kwabe\documents\!python proj\!nea\nea1\nea2\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kwabe\documents\!python proj\!nea\nea1\nea2\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\kwabe\documents\!python proj\!nea\nea1\nea2\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\kwabe\documents\!python proj\!nea\nea1\nea2\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\routes.py", line 248, in createApp
    queue1=createQueryQueue(query1)
  File "C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\query_count.py", line 8, in createQueryQueue
    if query.count() > 10:
TypeError: list.count() takes exactly one argument (0 given)
2023-01-27 21:58:43,195 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-01-31 16:53:42,139 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-02-01 18:53:55,253 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-02-03 20:30:48,425 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-02-06 11:56:07,561 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-02-06 14:12:06,760 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-02-09 08:38:59,716 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-02-16 10:40:35,449 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-02-16 12:51:32,819 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-02-23 13:35:35,240 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-02-24 10:58:22,808 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-02-24 11:14:25,539 ERROR: Exception on /viewHist/1 [GET] [in c:\users\kwabe\documents\!python proj\!nea\nea1\nea2\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\kwabe\documents\!python proj\!nea\nea1\nea2\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kwabe\documents\!python proj\!nea\nea1\nea2\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\kwabe\documents\!python proj\!nea\nea1\nea2\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\kwabe\documents\!python proj\!nea\nea1\nea2\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\routes.py", line 437, in viewHist
    return render_template('hist_viewer.html',allowed=allowed,illness_hist=illness_hist,id=id,isP=isP,fn=fn,sn=sn)
  File "c:\users\kwabe\documents\!python proj\!nea\nea1\nea2\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\kwabe\documents\!python proj\!nea\nea1\nea2\venv\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\kwabe\documents\!python proj\!nea\nea1\nea2\venv\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "c:\users\kwabe\documents\!python proj\!nea\nea1\nea2\venv\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "c:\users\kwabe\documents\!python proj\!nea\nea1\nea2\venv\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "c:\users\kwabe\documents\!python proj\!nea\nea1\nea2\venv\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "c:\users\kwabe\documents\!python proj\!nea\nea1\nea2\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\templates\hist_viewer.html", line 5, in template
    {% if (allowed==True or (illness_hist.NHSNumber=current_user.NHSNumber)) %}
jinja2.exceptions.TemplateSyntaxError: expected token ')', got '='
2023-02-24 11:14:50,176 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-02-24 11:16:42,199 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-02-24 11:17:09,728 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-02-24 11:26:19,341 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-02-27 12:06:32,487 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-02-27 12:37:35,093 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-02-27 12:38:01,672 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-02-27 12:39:52,232 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-02-27 12:43:57,220 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-02-27 13:54:48,324 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-02-27 14:04:00,013 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-02-28 22:14:36,374 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-03-01 11:10:29,087 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-03-04 07:55:26,980 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
2023-03-04 08:05:24,023 INFO: NEA2 startup [in C:\Users\kwabe\Documents\!Python Proj\!NEA\NEA1\NEA2\app\__init__.py:38]
